import type { TProfileLocale } from './types';

export const profileCopy = {
	ru: {
		title: 'Личный кабинет',
		welcome: 'Добро пожаловать',
		welcomeFallback: 'гость',
		greeting: 'Хорошего дня и вкусного кофе',
		edit: 'Редактировать',
		bonusTitle: 'Бонусная программа',
		bonusText: 'У вас',
		bonuses: 'бонусов',
		bonusLink: 'Как это работает?',
		bonusDescription:
			'Используйте бонусы при оформлении заказов и получайте приятные подарки.',
		orders: 'Мои заказы',
		bookings: 'Мои бронирования',
		allOrders: 'Все',
		processingOrders: 'В обработке',
		readyOrders: 'Готовы',
		completedOrders: 'Завершённые',
		favorites: 'Избранное',
		emptyFavorites: 'В избранном пока ничего нет',
		emptyFavoritesText:
			'Сохраняйте понравившиеся позиции, чтобы быстро найти их позже.',
		personalData: 'Личные данные',
		changePassword: 'Сменить пароль',
		settingsDescription:
			'Управляйте безопасностью аккаунта и выходом из системы.',
		deleteAccount: 'Удалить аккаунт',
		name: 'Имя',
		email: 'Email',
		phone: 'Телефон',
		birthDate: 'Дата рождения',
		emptyOrders: 'Здесь появятся ваши заказы',
		emptyOrdersText:
			'Оформите первую бронь или заказ, чтобы увидеть историю.',
		explore: 'Перейти к меню',
		emptyBookings: 'Здесь появятся ваши бронирования',
		emptyBookingsText:
			'Забронируйте столик, чтобы увидеть свои будущие посещения.',
		makeBooking: 'Забронировать столик',
		home: 'На главную',
		promoTitle: 'Твой следующий кофе — ближе, чем ты думаешь',
		promoText: 'Используй бонусы и получай приятные подарки.',
		promoButton: 'Посмотреть меню',
		sidebar: {
			profile: 'Мой профиль',
			orders: 'Мои заказы',
			favorites: 'Избранное',
			bonuses: 'Бонусы',
			settings: 'Настройки',
			logout: 'Выйти',
		},
	},
	en: {
		title: 'Personal account',
		welcome: 'Hello',
		welcomeFallback: 'guest',
		greeting: 'Have a lovely day and a delicious coffee',
		edit: 'Edit profile',
		bonusTitle: 'Bonus program',
		bonusText: 'You have',
		bonuses: 'bonuses',
		bonusLink: 'How does it work?',
		bonusDescription:
			'Use bonuses when placing orders and receive lovely gifts.',
		orders: 'My orders',
		bookings: 'My bookings',
		allOrders: 'All',
		processingOrders: 'In progress',
		readyOrders: 'Ready',
		completedOrders: 'Completed',
		favorites: 'Favorites',
		emptyFavorites: 'Your favorites are empty',
		emptyFavoritesText: 'Save items you like to find them quickly later.',
		personalData: 'Personal details',
		changePassword: 'Change password',
		settingsDescription:
			'Manage your account security and sign-out options.',
		deleteAccount: 'Delete account',
		name: 'Name',
		email: 'Email',
		phone: 'Phone',
		birthDate: 'Date of birth',
		emptyOrders: 'Your orders will appear here',
		emptyOrdersText: 'Make your first booking or order to see your history.',
		explore: 'Explore the menu',
		emptyBookings: 'Your bookings will appear here',
		emptyBookingsText: 'Book a table to see your upcoming visits.',
		makeBooking: 'Book a table',
		home: 'Home',
		promoTitle: 'Your next coffee is closer than you think',
		promoText: 'Use your bonuses and receive lovely gifts.',
		promoButton: 'View the menu',
		sidebar: {
			profile: 'My profile',
			orders: 'My orders',
			favorites: 'Favorites',
			bonuses: 'Bonuses',
			settings: 'Settings',
			logout: 'Sign out',
		},
	},
	he: {
		title: 'אזור אישי',
		welcome: 'שלום',
		welcomeFallback: 'אורח',
		greeting: 'שיהיה לך יום נעים וקפה טעים',
		edit: 'עריכת פרופיל',
		bonusTitle: 'תוכנית הטבות',
		bonusText: 'יש לך',
		bonuses: 'נקודות',
		bonusLink: 'איך זה עובד?',
		bonusDescription:
			'השתמשו בנקודות בעת ביצוע הזמנות וקבלו מתנות נעימות.',
		orders: 'ההזמנות שלי',
		bookings: 'הזמנות שולחן',
		allOrders: 'הכל',
		processingOrders: 'בטיפול',
		readyOrders: 'מוכן',
		completedOrders: 'הושלם',
		favorites: 'מועדפים',
		emptyFavorites: 'אין עדיין פריטים מועדפים',
		emptyFavoritesText:
			'שמרו פריטים שאהבתם כדי למצוא אותם בקלות בהמשך.',
		personalData: 'פרטים אישיים',
		changePassword: 'שינוי סיסמה',
		settingsDescription:
			'ניהול אבטחת החשבון ואפשרויות ההתנתקות.',
		deleteAccount: 'מחיקת חשבון',
		name: 'שם',
		email: 'אימייל',
		phone: 'טלפון',
		birthDate: 'תאריך לידה',
		emptyOrders: 'ההזמנות שלך יופיעו כאן',
		emptyOrdersText:
			'בצעו הזמנה ראשונה כדי לראות את ההיסטוריה שלכם.',
		explore: 'למעבר לתפריט',
		emptyBookings: 'ההזמנות שלך יופיעו כאן',
		emptyBookingsText:
			'הזמינו שולחן כדי לראות את הביקורים הקרובים שלכם.',
		makeBooking: 'להזמנת שולחן',
		home: 'דף הבית',
		promoTitle: 'הקפה הבא שלך קרוב יותר ממה שנדמה',
		promoText: 'השתמשו בנקודות וקבלו מתנות נעימות.',
		promoButton: 'לצפייה בתפריט',
		sidebar: {
			profile: 'הפרופיל שלי',
			orders: 'ההזמנות שלי',
			favorites: 'מועדפים',
			bonuses: 'הטבות',
			settings: 'הגדרות',
			logout: 'התנתקות',
		},
	},
} as const satisfies Record<TProfileLocale, object>;

export type TProfileCopy = (typeof profileCopy)[TProfileLocale];
