import type { TProfileLocale } from './types';

export const profileCopy = {
	ru: {
		title: 'Личный кабинет',
		welcome: 'Добро пожаловать',
		welcomeFallback: 'гость',
		greeting: 'Хорошего дня и вкусного кофе',
		edit: 'Редактировать',
		editingProfile: 'Редактирование профиля',
		firstName: 'Имя',
		lastName: 'Фамилия',
		save: 'Сохранить',
		saving: 'Сохраняем...',
		cancel: 'Отмена',
		profileUpdated: 'Данные профиля обновлены.',
		profileUpdateError: 'Не удалось обновить данные профиля.',
		invalidPhone: 'Введите корректный номер телефона.',
		phoneAlreadyExists: 'Этот номер телефона уже используется другим аккаунтом.',
		deleteConfirm:
			'Удалить аккаунт? Все данные аккаунта будут удалены без возможности восстановления.',
		deleting: 'Удаляем...',
		deleteError: 'Не удалось удалить аккаунт. Попробуйте ещё раз.',
		currentPassword: 'Текущий пароль',
		verificationCode: 'Код из email',
		sendCode: 'Получить код',
		codeSent: 'Код отправлен на вашу почту.',
		invalidPassword: 'Неверный текущий пароль.',
		invalidCode: 'Неверный или просроченный код.',
		verifying: 'Проверяем...',
		requiredProfileFields: 'Заполните имя, фамилию, телефон и дату рождения.',
		bonusTitle: 'Бонусная программа',
		bonusText: 'У вас',
		bonuses: 'бонусов',
		bonusLink: 'Как это работает?',
		bonusDescription:
			'Используйте бонусы при оформлении заказов и получайте приятные подарки.',
		orders: 'Мои заказы',
		bookings: 'Мои бронирования',
		allOrders: 'Все',
		processingOrders: 'В обработке',
		readyOrders: 'Готовы',
		completedOrders: 'Завершённые',
		favorites: 'Избранное',
		emptyFavorites: 'В избранном пока ничего нет',
		emptyFavoritesText:
			'Сохраняйте понравившиеся позиции, чтобы быстро найти их позже.',
		personalData: 'Личные данные',
		changePassword: 'Сменить пароль',
		changePasswordDescription:
			'Введите новый пароль для вашего аккаунта.',
		newPassword: 'Новый пароль',
		confirmNewPassword: 'Повторите новый пароль',
		savePassword: 'Сменить пароль',
		changingPassword: 'Сохраняем...',
		passwordChanged: 'Пароль успешно изменён.',
		passwordLength: 'Пароль должен содержать минимум 6 символов.',
		passwordMismatch: 'Пароли не совпадают.',
		passwordChangeError:
			'Не удалось изменить пароль. Попробуйте ещё раз.',
		showPassword: 'Показать пароль',
		hidePassword: 'Скрыть пароль',
		settingsDescription:
			'Управляйте безопасностью аккаунта и выходом из системы.',
		activeDevices: 'Активные устройства',
		activeDevicesDescription:
			'Устройства и браузеры, на которых открыт ваш аккаунт.',
		currentDevice: 'Текущее устройство',
		desktopDevice: 'Компьютер',
		mobileDevice: 'Телефон',
		tabletDevice: 'Планшет',
		unknownDevice: 'Неизвестное устройство',
		mobileApp: 'Мобильное приложение',
		lastActive: 'Последняя активность',
		sessionsLoading: 'Загружаем активные устройства...',
		sessionsError: 'Не удалось загрузить активные устройства.',
		noActiveDevices: 'Активные устройства не найдены.',
		signOutAllDevices: 'Выйти на других устройствах',
		signingOutAllDevices: 'Завершаем другие сеансы...',
		otherDevicesSignedOut: 'На остальных устройствах выполнен выход.',
		signOutAllDevicesConfirm:
			'Выйти из аккаунта на всех остальных устройствах? Текущий сеанс останется активным.',
		signOutAllDevicesError:
			'Не удалось завершить все сеансы. Попробуйте ещё раз.',
		deleteAccount: 'Удалить аккаунт',
		name: 'Имя',
		email: 'Email',
		phone: 'Телефон',
		birthDate: 'Дата рождения',
		emptyOrders: 'Здесь появятся ваши заказы',
		emptyOrdersText:
			'Оформите первую бронь или заказ, чтобы увидеть историю.',
		explore: 'Перейти к меню',
		emptyBookings: 'Здесь появятся ваши бронирования',
		emptyBookingsText:
			'Забронируйте столик, чтобы увидеть свои будущие посещения.',
		makeBooking: 'Забронировать столик',
		home: 'На главную',
		adminPanel: 'Админ-панель',
		promoTitle: 'Твой следующий кофе — ближе, чем ты думаешь',
		promoText: 'Используй бонусы и получай приятные подарки.',
		promoButton: 'Посмотреть меню',
		sidebar: {
			profile: 'Мой профиль',
			orders: 'Мои заказы',
			favorites: 'Избранное',
			bonuses: 'Бонусы',
			settings: 'Настройки',
			logout: 'Выйти',
		},
	},
	en: {
		title: 'Personal account',
		welcome: 'Hello',
		welcomeFallback: 'guest',
		greeting: 'Have a lovely day and a delicious coffee',
		edit: 'Edit profile',
		editingProfile: 'Edit profile',
		firstName: 'First name',
		lastName: 'Last name',
		save: 'Save changes',
		saving: 'Saving...',
		cancel: 'Cancel',
		profileUpdated: 'Profile details updated.',
		profileUpdateError: 'Could not update your profile details.',
		invalidPhone: 'Enter a valid phone number.',
		phoneAlreadyExists: 'This phone number is already used by another account.',
		deleteConfirm:
			'Delete your account? All account data will be permanently removed.',
		deleting: 'Deleting...',
		deleteError: 'Could not delete your account. Please try again.',
		currentPassword: 'Current password',
		verificationCode: 'Email verification code',
		sendCode: 'Send code',
		codeSent: 'A verification code was sent to your email.',
		invalidPassword: 'The current password is incorrect.',
		invalidCode: 'The code is invalid or expired.',
		verifying: 'Verifying...',
		requiredProfileFields: 'Fill in your first name, last name, phone, and birth date.',
		bonusTitle: 'Bonus program',
		bonusText: 'You have',
		bonuses: 'bonuses',
		bonusLink: 'How does it work?',
		bonusDescription:
			'Use bonuses when placing orders and receive lovely gifts.',
		orders: 'My orders',
		bookings: 'My bookings',
		allOrders: 'All',
		processingOrders: 'In progress',
		readyOrders: 'Ready',
		completedOrders: 'Completed',
		favorites: 'Favorites',
		emptyFavorites: 'Your favorites are empty',
		emptyFavoritesText: 'Save items you like to find them quickly later.',
		personalData: 'Personal details',
		changePassword: 'Change password',
		changePasswordDescription:
			'Enter a new password for your account.',
		newPassword: 'New password',
		confirmNewPassword: 'Confirm new password',
		savePassword: 'Change password',
		changingPassword: 'Saving...',
		passwordChanged: 'Your password has been changed.',
		passwordLength: 'Password must contain at least 6 characters.',
		passwordMismatch: 'Passwords do not match.',
		passwordChangeError:
			'Could not change your password. Please try again.',
		showPassword: 'Show password',
		hidePassword: 'Hide password',
		settingsDescription:
			'Manage your account security and sign-out options.',
		activeDevices: 'Active devices',
		activeDevicesDescription:
			'Devices and browsers where your account is signed in.',
		currentDevice: 'Current device',
		desktopDevice: 'Computer',
		mobileDevice: 'Phone',
		tabletDevice: 'Tablet',
		unknownDevice: 'Unknown device',
		mobileApp: 'Mobile app',
		lastActive: 'Last active',
		sessionsLoading: 'Loading active devices...',
		sessionsError: 'Could not load active devices.',
		noActiveDevices: 'No active devices found.',
		signOutAllDevices: 'Sign out on other devices',
		signingOutAllDevices: 'Signing out other devices...',
		otherDevicesSignedOut: 'All other devices have been signed out.',
		signOutAllDevicesConfirm:
			'Sign out of your account on every other device? Your current session will stay active.',
		signOutAllDevicesError:
			'Could not sign out all devices. Please try again.',
		deleteAccount: 'Delete account',
		name: 'Name',
		email: 'Email',
		phone: 'Phone',
		birthDate: 'Date of birth',
		emptyOrders: 'Your orders will appear here',
		emptyOrdersText: 'Make your first booking or order to see your history.',
		explore: 'Explore the menu',
		emptyBookings: 'Your bookings will appear here',
		emptyBookingsText: 'Book a table to see your upcoming visits.',
		makeBooking: 'Book a table',
		home: 'Home',
		adminPanel: 'Admin panel',
		promoTitle: 'Your next coffee is closer than you think',
		promoText: 'Use your bonuses and receive lovely gifts.',
		promoButton: 'View the menu',
		sidebar: {
			profile: 'My profile',
			orders: 'My orders',
			favorites: 'Favorites',
			bonuses: 'Bonuses',
			settings: 'Settings',
			logout: 'Sign out',
		},
	},
	he: {
		title: 'אזור אישי',
		welcome: 'שלום',
		welcomeFallback: 'אורח',
		greeting: 'שיהיה לך יום נעים וקפה טעים',
		edit: 'עריכת פרופיל',
		editingProfile: 'עריכת פרופיל',
		firstName: 'שם פרטי',
		lastName: 'שם משפחה',
		save: 'שמירת שינויים',
		saving: 'שומר...',
		cancel: 'ביטול',
		profileUpdated: 'פרטי הפרופיל עודכנו.',
		profileUpdateError: 'לא ניתן לעדכן את פרטי הפרופיל.',
		invalidPhone: 'יש להזין מספר טלפון תקין.',
		phoneAlreadyExists: 'מספר הטלפון הזה כבר משויך לחשבון אחר.',
		deleteConfirm:
			'למחוק את החשבון? כל נתוני החשבון יימחקו לצמיתות.',
		deleting: 'מוחק...',
		deleteError: 'לא ניתן למחוק את החשבון. יש לנסות שוב.',
		currentPassword: 'סיסמה נוכחית',
		verificationCode: 'קוד אימות מהאימייל',
		sendCode: 'שליחת קוד',
		codeSent: 'קוד אימות נשלח לאימייל שלך.',
		invalidPassword: 'הסיסמה הנוכחית שגויה.',
		invalidCode: 'הקוד שגוי או שפג תוקפו.',
		verifying: 'מאמת...',
		requiredProfileFields: 'יש למלא שם פרטי, שם משפחה, טלפון ותאריך לידה.',
		bonusTitle: 'תוכנית הטבות',
		bonusText: 'יש לך',
		bonuses: 'נקודות',
		bonusLink: 'איך זה עובד?',
		bonusDescription:
			'השתמשו בנקודות בעת ביצוע הזמנות וקבלו מתנות נעימות.',
		orders: 'ההזמנות שלי',
		bookings: 'הזמנות שולחן',
		allOrders: 'הכל',
		processingOrders: 'בטיפול',
		readyOrders: 'מוכן',
		completedOrders: 'הושלם',
		favorites: 'מועדפים',
		emptyFavorites: 'אין עדיין פריטים מועדפים',
		emptyFavoritesText:
			'שמרו פריטים שאהבתם כדי למצוא אותם בקלות בהמשך.',
		personalData: 'פרטים אישיים',
		changePassword: 'שינוי סיסמה',
		changePasswordDescription:
			'יש להזין סיסמה חדשה לחשבון.',
		newPassword: 'סיסמה חדשה',
		confirmNewPassword: 'אימות הסיסמה החדשה',
		savePassword: 'שינוי סיסמה',
		changingPassword: 'שומר...',
		passwordChanged: 'הסיסמה שונתה בהצלחה.',
		passwordLength: 'הסיסמה חייבת לכלול לפחות 6 תווים.',
		passwordMismatch: 'הסיסמאות אינן תואמות.',
		passwordChangeError:
			'לא ניתן לשנות את הסיסמה. יש לנסות שוב.',
		showPassword: 'הצגת הסיסמה',
		hidePassword: 'הסתרת הסיסמה',
		settingsDescription:
			'ניהול אבטחת החשבון ואפשרויות ההתנתקות.',
		activeDevices: 'מכשירים פעילים',
		activeDevicesDescription:
			'מכשירים ודפדפנים שבהם החשבון שלך מחובר.',
		currentDevice: 'המכשיר הנוכחי',
		desktopDevice: 'מחשב',
		mobileDevice: 'טלפון',
		tabletDevice: 'טאבלט',
		unknownDevice: 'מכשיר לא מוכר',
		mobileApp: 'אפליקציה לנייד',
		lastActive: 'פעילות אחרונה',
		sessionsLoading: 'טוען מכשירים פעילים...',
		sessionsError: 'לא ניתן לטעון את המכשירים הפעילים.',
		noActiveDevices: 'לא נמצאו מכשירים פעילים.',
		signOutAllDevices: 'יציאה ממכשירים אחרים',
		signingOutAllDevices: 'מתנתק ממכשירים אחרים...',
		otherDevicesSignedOut: 'החשבון נותק מכל המכשירים האחרים.',
		signOutAllDevicesConfirm:
			'להתנתק מהחשבון בכל המכשירים האחרים? החיבור במכשיר הנוכחי יישאר פעיל.',
		signOutAllDevicesError:
			'לא ניתן להתנתק מכל המכשירים. יש לנסות שוב.',
		deleteAccount: 'מחיקת חשבון',
		name: 'שם',
		email: 'אימייל',
		phone: 'טלפון',
		birthDate: 'תאריך לידה',
		emptyOrders: 'ההזמנות שלך יופיעו כאן',
		emptyOrdersText:
			'בצעו הזמנה ראשונה כדי לראות את ההיסטוריה שלכם.',
		explore: 'למעבר לתפריט',
		emptyBookings: 'ההזמנות שלך יופיעו כאן',
		emptyBookingsText:
			'הזמינו שולחן כדי לראות את הביקורים הקרובים שלכם.',
		makeBooking: 'להזמנת שולחן',
		home: 'דף הבית',
		adminPanel: 'לוח ניהול',
		promoTitle: 'הקפה הבא שלך קרוב יותר ממה שנדמה',
		promoText: 'השתמשו בנקודות וקבלו מתנות נעימות.',
		promoButton: 'לצפייה בתפריט',
		sidebar: {
			profile: 'הפרופיל שלי',
			orders: 'ההזמנות שלי',
			favorites: 'מועדפים',
			bonuses: 'הטבות',
			settings: 'הגדרות',
			logout: 'התנתקות',
		},
	},
} as const satisfies Record<TProfileLocale, object>;

export type TProfileCopy = (typeof profileCopy)[TProfileLocale];
