import { StyleSheet } from 'react-native';
import { Colors, Fonts, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
	screen: { flex: 1, backgroundColor: Colors.background },
	content: { paddingBottom: 48 },
	hero: { paddingHorizontal: Spacing.medium, paddingTop: 28, paddingBottom: 24, backgroundColor: '#EFE4D8' },
	eyebrow: { color: '#8A6D5A', fontFamily: Fonts.sans, fontSize: 11, fontWeight: '700', letterSpacing: 1.4, textTransform: 'uppercase' },
	title: { marginTop: 8, color: Colors.foreground, fontFamily: Fonts.serif, fontSize: 42, lineHeight: 46 },
	description: { marginTop: 10, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 22 },
	rtlText: { textAlign: 'right', writingDirection: 'rtl' },
	filters: { paddingHorizontal: Spacing.medium, paddingVertical: 18, gap: 8 },
	filter: { minHeight: 40, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DDCFC2', borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.65)' },
	activeFilter: { borderColor: Colors.accent, backgroundColor: Colors.accent },
	filterText: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '600' },
	activeFilterText: { color: Colors.white },
	list: { marginBottom: 16, paddingHorizontal: Spacing.medium },
	card: { minHeight: 500, overflow: 'hidden', borderWidth: 1, borderColor: '#DFD2C5', borderRadius: 24, backgroundColor: '#FFFCF9' },
	image: { width: '100%', height: 250 },
	imageWrap: { position: 'relative' },
	typeBadge: { position: 'absolute', top: 14, left: 14, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.94)' },
	typeBadgeRtl: { left: undefined, right: 14 },
	typeText: { color: '#725542', fontFamily: Fonts.sans, fontSize: 11, fontWeight: '700' },
	cardBody: { flex: 1, padding: 18 },
	date: { color: '#8A6D5A', fontFamily: Fonts.sans, fontSize: 11, fontWeight: '700', letterSpacing: 0.8, textTransform: 'uppercase' },
	cardTitle: { minHeight: 62, marginTop: 8, color: Colors.foreground, fontFamily: Fonts.serif, fontSize: 28, lineHeight: 31 },
	cardDescription: { minHeight: 66, marginTop: 8, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 22 },
	cardFooter: { marginTop: 'auto', paddingTop: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
	meta: { flexDirection: 'row', alignItems: 'center', gap: 6 },
	metaText: { color: '#725542', fontFamily: Fonts.sans, fontSize: 12, fontWeight: '600' },
	detailButton: { minHeight: 40, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 999, backgroundColor: Colors.accent },
	detailButtonText: { color: Colors.white, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '700' },
	loading: { minHeight: 500, alignItems: 'center', justifyContent: 'center' },
	empty: { minHeight: 500, marginHorizontal: Spacing.medium, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderStyle: 'dashed', borderColor: '#D8C8BA', borderRadius: 24 },
	emptyText: { marginTop: 10, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 14, textAlign: 'center' },
	loadError: { marginHorizontal: Spacing.medium, marginTop: 12, padding: 12, color: '#AD493F', fontFamily: Fonts.sans, fontSize: 12, textAlign: 'center', borderRadius: 14, backgroundColor: '#FFF1EF' },
	backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(33,22,15,0.55)' },
	dialog: { maxHeight: '90%', overflow: 'hidden', borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: '#FFFAF5' },
	dialogImage: { width: '100%', height: 220 },
	close: { position: 'absolute', top: 14, right: 14, width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.94)' },
	closeRtl: { right: undefined, left: 14 },
	dialogContent: { padding: 20, paddingBottom: 34 },
	dialogTitle: { marginTop: 12, color: Colors.foreground, fontFamily: Fonts.serif, fontSize: 34, lineHeight: 38 },
	dialogDescription: { marginTop: 10, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 14, lineHeight: 23 },
	info: { marginTop: 16, gap: 10, padding: 14, borderRadius: 18, backgroundColor: '#F3E8DC' },
	infoRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
	infoLabel: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 12 },
	infoValue: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '700' },
	guestLabel: { marginTop: 18, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '600' },
	guestRow: { marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 14 },
	stepperButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D8CABD', borderRadius: 21, backgroundColor: Colors.white },
	disabled: { opacity: 0.42 },
	guestCount: { minWidth: 28, color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 18, fontWeight: '700', textAlign: 'center' },
	primaryButton: { minHeight: 48, marginTop: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 999, backgroundColor: Colors.accent },
	primaryButtonText: { color: Colors.white, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
	status: { marginTop: 18, padding: 14, borderRadius: 16, backgroundColor: '#E7F0E2' },
	statusText: { color: '#526C48', fontFamily: Fonts.sans, fontSize: 14, fontWeight: '700' },
	cancelButton: { minHeight: 44, marginTop: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#F1C9C4', borderRadius: 999, backgroundColor: '#FFF1EF' },
	cancelText: { color: '#B64D45', fontFamily: Fonts.sans, fontSize: 13, fontWeight: '700' },
	message: { marginTop: 12, color: '#526C48', fontFamily: Fonts.sans, fontSize: 13 },
});
