import { StyleSheet } from 'react-native';

import { Colors, Fonts, Spacing } from '@/constants/theme';

export const profileContentStyles = StyleSheet.create({
	keyboardAvoiding: {
		flex: 1,
	},
	content: {
		padding: Spacing.medium,
		paddingBottom: Spacing.xLarge,
	},
	greeting: {
		marginTop: Spacing.medium,
		gap: 6,
	},
	eyebrow: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	title: {
		color: Colors.foreground,
		fontFamily: Fonts.serif,
		fontSize: 31,
		lineHeight: 38,
	},
	greetingText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 14,
	},
	editButton: {
		minHeight: 42,
		marginTop: Spacing.small,
		paddingHorizontal: Spacing.medium,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		alignSelf: 'flex-start',
		borderRadius: 999,
		backgroundColor: Colors.accent,
	},
	editButtonText: {
		color: Colors.white,
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '700',
	},
	bonusCard: {
		marginTop: Spacing.large,
		padding: Spacing.medium,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
		borderRadius: 18,
		backgroundColor: '#EFE4D8',
	},
	bonusIcon: {
		width: 44,
		height: 44,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 22,
		backgroundColor: Colors.background,
	},
	bonusCopy: {
		flex: 1,
		gap: 3,
	},
	bonusTitle: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 11,
		letterSpacing: 1,
		textTransform: 'uppercase',
	},
	bonusText: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 15,
		fontWeight: '600',
	},
	bonusValue: {
		color: Colors.accent,
	},
	tabs: {
		marginTop: Spacing.large,
		flexDirection: 'row',
		flexWrap: 'wrap',
	},
	tabsRtl: {
		flexDirection: 'row-reverse',
	},
	tab: {
		width: '33.333%',
		minHeight: 44,
		alignItems: 'center',
		justifyContent: 'center',
		borderBottomWidth: 2,
		borderBottomColor: 'transparent',
	},
	activeTab: {
		borderBottomColor: Colors.accent,
	},
	tabText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 12,
	},
	activeTabText: {
		color: Colors.foreground,
		fontWeight: '700',
	},
	detailsCard: {
		marginTop: Spacing.medium,
		padding: Spacing.medium,
		gap: Spacing.medium,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	profileIdentity: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	identityRtl: {
		flexDirection: 'row-reverse',
	},
	avatar: {
		width: 66,
		height: 66,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 33,
		backgroundColor: '#E7D7C8',
	},
	avatarText: {
		color: Colors.accent,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '600',
	},
	identityCopy: {
		flex: 1,
		gap: 4,
	},
	identityName: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '700',
	},
	identityEmail: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	identityPhone: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	rows: {
		paddingVertical: Spacing.small,
		borderTopWidth: StyleSheet.hairlineWidth,
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderColor: '#E5DCD3',
	},
	row: {
		minHeight: 42,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	rowRtl: {
		flexDirection: 'row-reverse',
	},
	rowLabel: {
		width: 96,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	rowValue: {
		flex: 1,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 13,
		fontWeight: '600',
		textAlign: 'right',
	},
	actionRow: {
		minHeight: 48,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	settingsCard: {
		marginTop: Spacing.medium,
		paddingHorizontal: Spacing.medium,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	settingsTitle: {
		marginTop: Spacing.medium,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '700',
	},
	settingsText: {
		marginTop: 5,
		marginBottom: Spacing.small,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
		lineHeight: 19,
	},
	actionText: {
		flex: 1,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '600',
	},
	logoutRow: {
		borderTopWidth: StyleSheet.hairlineWidth,
		borderColor: '#F3D2CE',
	},
	logoutText: {
		flex: 1,
		color: '#C95C52',
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '600',
	},
	list: {
		marginTop: Spacing.medium,
	},
	statuses: {
		padding: 4,
		flexDirection: 'row',
		gap: 4,
		borderRadius: 12,
		backgroundColor: '#EFE4D8',
	},
	status: {
		flex: 1,
		minHeight: 36,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 9,
	},
	activeStatus: {
		backgroundColor: Colors.background,
	},
	statusText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 11,
		fontWeight: '600',
	},
	emptyState: {
		marginTop: Spacing.medium,
		padding: Spacing.xLarge,
		alignItems: 'center',
		gap: Spacing.small,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	emptyIcon: {
		width: 52,
		height: 52,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 26,
		backgroundColor: '#EFE4D8',
	},
	emptyTitle: {
		marginTop: Spacing.small,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 17,
		fontWeight: '700',
		textAlign: 'center',
	},
	emptyText: {
		maxWidth: 280,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
		lineHeight: 19,
		textAlign: 'center',
	},
	pressed: {
		opacity: 0.65,
	},
	rtlText: {
		writingDirection: 'rtl',
		textAlign: 'right',
	},
	ltrText: {
		writingDirection: 'ltr',
	},
});
