import { StyleSheet } from 'react-native';

import { Colors, Fonts, Spacing } from '@/constants/theme';

export const profileContentStyles = StyleSheet.create({
	keyboardAvoiding: {
		flex: 1,
	},
	content: {
		padding: Spacing.medium,
		paddingBottom: Spacing.xLarge,
	},
	greeting: {
		marginTop: Spacing.medium,
		gap: 6,
	},
	eyebrow: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	title: {
		color: Colors.foreground,
		fontFamily: Fonts.serif,
		fontSize: 31,
		lineHeight: 38,
	},
	greetingText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 14,
	},
	editButton: {
		minHeight: 42,
		marginTop: Spacing.small,
		paddingHorizontal: Spacing.medium,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		alignSelf: 'flex-start',
		borderRadius: 999,
		backgroundColor: Colors.accent,
	},
	editButtonText: {
		color: Colors.white,
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '700',
	},
	bonusCard: {
		marginTop: Spacing.large,
		padding: Spacing.medium,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
		borderRadius: 18,
		backgroundColor: '#EFE4D8',
	},
	bonusIcon: {
		width: 44,
		height: 44,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 22,
		backgroundColor: Colors.background,
	},
	bonusCopy: {
		flex: 1,
		gap: 3,
	},
	bonusTitle: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 11,
		letterSpacing: 1,
		textTransform: 'uppercase',
	},
	bonusText: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 15,
		fontWeight: '600',
	},
	bonusValue: {
		color: Colors.accent,
	},
	tabs: {
		marginTop: Spacing.large,
		flexDirection: 'row',
		flexWrap: 'wrap',
	},
	tabsRtl: {
		flexDirection: 'row-reverse',
	},
	tab: {
		width: '33.333%',
		minHeight: 44,
		alignItems: 'center',
		justifyContent: 'center',
		borderBottomWidth: 2,
		borderBottomColor: 'transparent',
	},
	activeTab: {
		borderBottomColor: Colors.accent,
	},
	tabText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 12,
	},
	activeTabText: {
		color: Colors.foreground,
		fontWeight: '700',
	},
	detailsCard: {
		marginTop: Spacing.medium,
		padding: Spacing.medium,
		gap: Spacing.medium,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	profileIdentity: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	identityRtl: {
		flexDirection: 'row-reverse',
	},
	avatar: {
		width: 66,
		height: 66,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 33,
		backgroundColor: '#E7D7C8',
	},
	avatarText: {
		color: Colors.accent,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '600',
	},
	identityCopy: {
		flex: 1,
		gap: 4,
	},
	identityName: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '700',
	},
	identityEmail: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	identityPhone: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	rows: {
		paddingVertical: Spacing.small,
		borderTopWidth: StyleSheet.hairlineWidth,
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderColor: '#E5DCD3',
	},
	row: {
		minHeight: 42,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	rowRtl: {
		flexDirection: 'row-reverse',
	},
	rowLabel: {
		width: 96,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	rowValue: {
		flex: 1,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 13,
		fontWeight: '600',
		textAlign: 'right',
	},
	actionRow: {
		minHeight: 48,
		flexDirection: 'row',
		alignItems: 'center',
		gap: Spacing.small,
	},
	settingsCard: {
		marginTop: Spacing.medium,
		paddingHorizontal: Spacing.medium,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	settingsTitle: {
		marginTop: Spacing.medium,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '700',
	},
	settingsText: {
		marginTop: 5,
		marginBottom: Spacing.small,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
		lineHeight: 19,
	},
	actionText: {
		flex: 1,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '600',
	},
	logoutRow: {
		borderTopWidth: StyleSheet.hairlineWidth,
		borderColor: '#F3D2CE',
	},
	logoutText: {
		flex: 1,
		color: '#C95C52',
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '600',
	},
	list: {
		marginTop: Spacing.medium,
	},
	productLoading: {
		minHeight: 150,
		marginTop: Spacing.medium,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	productList: {
		marginTop: Spacing.medium,
		gap: Spacing.small,
	},
	orderCard: {
		overflow: 'hidden',
		borderWidth: 1,
		borderColor: '#E1D4C8',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.82)',
	},
	completedOrderCard: { borderColor: '#D8D2CC', backgroundColor: 'rgba(244,241,238,0.85)' },
	orderHeader: {
		paddingHorizontal: 14,
		paddingVertical: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
		backgroundColor: '#EFE4D8',
	},
	orderHeadingCopy: { minWidth: 0, flex: 1, gap: 3 },
	orderHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
	orderChevron: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 15, backgroundColor: 'rgba(255,255,255,0.65)' },
	orderChevronOpen: { transform: [{ rotate: '180deg' }] },
	orderNumber: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 14, fontWeight: '800' },
	orderDate: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 10 },
	orderProgress: { paddingHorizontal: 10, paddingVertical: 14, flexDirection: 'row', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#EADFD5', backgroundColor: 'rgba(255,255,255,0.45)' },
	orderStep: { position: 'relative', flex: 1, alignItems: 'center' },
	orderStepLine: { position: 'absolute', top: 11, right: '50%', width: '100%', height: 2, backgroundColor: '#DDD3CA' },
	orderStepLineActive: { backgroundColor: '#7B8F70' },
	orderStepDot: { zIndex: 1, width: 24, height: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D8CCC1', borderRadius: 12, backgroundColor: '#F8F3EC' },
	orderStepDotActive: { borderColor: '#6D825F', backgroundColor: '#6D825F' },
	orderStepNumber: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 10, fontWeight: '700' },
	orderStepNumberActive: { color: Colors.white },
	orderStepLabel: { marginTop: 6, maxWidth: '94%', color: Colors.muted, fontFamily: Fonts.sans, fontSize: 9, textAlign: 'center' },
	orderStepLabelActive: { color: Colors.foreground, fontWeight: '700' },
	orderItems: { paddingHorizontal: 14 },
	orderItem: {
		minHeight: 72,
		paddingVertical: 10,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: '#EADFD5',
	},
	orderItemImage: { width: 58, height: 52, borderRadius: 9, backgroundColor: '#EFE4D7' },
	orderItemCopy: { minWidth: 0, flex: 1, gap: 3 },
	orderItemName: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '700' },
	orderItemQuantity: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 11 },
	orderItemPrice: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 12, fontWeight: '800', writingDirection: 'ltr' },
	orderFooter: {
		paddingHorizontal: 14,
		paddingVertical: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	orderItemCount: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 11 },
	orderTotal: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '800', writingDirection: 'ltr' },
	productRow: {
		padding: 10,
		flexDirection: 'row',
		gap: 12,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 16,
		backgroundColor: 'rgba(255, 255, 255, 0.82)',
	},
	productImage: {
		width: 104,
		height: 88,
		borderRadius: 12,
		backgroundColor: '#EFE4D7',
	},
	productRowContent: {
		minWidth: 0,
		flex: 1,
	},
	productRowHeader: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 8,
	},
	productRowCopy: {
		minWidth: 0,
		flex: 1,
	},
	productRowName: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 14,
		fontWeight: '700',
	},
	productRowDescription: {
		marginTop: 3,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 11,
		lineHeight: 16,
	},
	removeFavorite: {
		width: 34,
		height: 34,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 17,
		backgroundColor: '#F3E8DF',
	},
	productRowFooter: {
		marginTop: 8,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
	},
	productRowPrice: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 13,
		fontWeight: '800',
		writingDirection: 'ltr',
	},
	orderStatus: {
		overflow: 'hidden',
		paddingHorizontal: 9,
		paddingVertical: 5,
		color: '#526C48',
		fontFamily: Fonts.sans,
		fontSize: 10,
		fontWeight: '700',
		borderRadius: 999,
		backgroundColor: '#E7F0E2',
	},
	processingOrderStatus: { color: '#8A621B', backgroundColor: '#FFF2D9' },
	preparingOrderStatus: { color: '#8A5528', backgroundColor: '#F6E6D4' },
	readyOrderStatus: { color: '#526C48', backgroundColor: '#E7F0E2' },
	completedOrderStatus: { color: '#675E58', backgroundColor: '#ECE8E4' },
	cancelledOrderStatus: { color: '#9A433D', backgroundColor: '#F7E3DF' },
	cancelOrderButton: { minHeight: 42, marginHorizontal: 13, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#E6BDB5', borderRadius: 21, backgroundColor: '#FFF5F2' },
	cancelOrderText: { color: '#A64338', fontFamily: Fonts.sans, fontSize: 11, fontWeight: '800' },
	cancelOrderError: { marginHorizontal: 13, marginBottom: 10, color: '#B33A3A', fontFamily: Fonts.sans, fontSize: 10, textAlign: 'center' },
	statuses: {
		padding: 4,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 4,
		borderRadius: 12,
		backgroundColor: '#EFE4D8',
	},
	status: {
		flexBasis: '31%',
		flexGrow: 1,
		minHeight: 36,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 9,
	},
	activeStatus: {
		backgroundColor: Colors.background,
	},
	statusText: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 11,
		fontWeight: '600',
	},
	emptyState: {
		marginTop: Spacing.medium,
		padding: Spacing.xLarge,
		alignItems: 'center',
		gap: Spacing.small,
		borderWidth: 1,
		borderColor: '#E5DCD3',
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.78)',
	},
	emptyIcon: {
		width: 52,
		height: 52,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 26,
		backgroundColor: '#EFE4D8',
	},
	emptyTitle: {
		marginTop: Spacing.small,
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 17,
		fontWeight: '700',
		textAlign: 'center',
	},
	emptyText: {
		maxWidth: 280,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
		lineHeight: 19,
		textAlign: 'center',
	},
	pressed: {
		opacity: 0.65,
	},
	rtlText: {
		writingDirection: 'rtl',
		textAlign: 'right',
	},
	ltrText: {
		writingDirection: 'ltr',
	},
});
