import { StyleSheet } from 'react-native';

import { Colors, Fonts, Spacing } from '@/constants/theme';

export const adminOverviewStyles = StyleSheet.create({
	wrapper: {
		gap: Spacing.medium,
	},
	statistics: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	rtlRow: {
		flexDirection: 'row-reverse',
	},
	statCard: {
		width: '48.5%',
		minHeight: 150,
		padding: Spacing.medium,
		justifyContent: 'space-between',
		borderWidth: 1,
		borderColor: '#E3D7CB',
		borderRadius: 20,
		backgroundColor: 'rgba(255,255,255,0.78)',
	},
	iconCircle: {
		width: 40,
		height: 40,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 20,
		backgroundColor: '#F0E4D7',
	},
	value: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 25,
		fontWeight: '700',
	},
	valueLoader: { alignSelf: 'flex-start', marginVertical: 5 },
	statLabel: {
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 13,
	},
	activityCard: {
		padding: Spacing.medium,
		borderWidth: 1,
		borderColor: '#E3D7CB',
		borderRadius: 24,
		backgroundColor: 'rgba(255,255,255,0.78)',
	},
	activityTitle: {
		color: Colors.foreground,
		fontFamily: Fonts.sans,
		fontSize: 18,
		fontWeight: '700',
	},
	activityHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
	allActivity: { flexDirection: 'row', alignItems: 'center', gap: 2 },
	allActivityText: { color: Colors.accent, fontFamily: Fonts.sans, fontSize: 11, fontWeight: '700' },
	loadingActivity: { minHeight: 190, marginTop: Spacing.medium, alignItems: 'center', justifyContent: 'center' },
	activityList: { marginTop: Spacing.medium, gap: 8 },
	activityRow: { minHeight: 76, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#E9DFD5', borderRadius: 16, backgroundColor: '#FBF8F4' },
	orderIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: '#EFE2D5' },
	activityCopy: { minWidth: 0, flex: 1 },
	orderTitle: { color: Colors.foreground, fontFamily: Fonts.sans, fontSize: 13, fontWeight: '700' },
	orderMeta: { marginTop: 4, color: Colors.muted, fontFamily: Fonts.sans, fontSize: 10 },
	activityStatus: { maxWidth: 108, alignItems: 'flex-end', gap: 5 },
	statusPill: { overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, fontFamily: Fonts.sans, fontSize: 9, fontWeight: '700', textAlign: 'center' },
	processingStatus: { color: '#8A621B', backgroundColor: '#FFF2D9' },
	preparingStatus: { color: '#8A5528', backgroundColor: '#F6E6D4' },
	readyStatus: { color: '#526C48', backgroundColor: '#E7F0E2' },
	completedStatus: { color: '#675E58', backgroundColor: '#ECE8E4' },
	cancelledStatus: { color: '#9A433D', backgroundColor: '#F7E3DF' },
	activityTime: { color: Colors.muted, fontFamily: Fonts.sans, fontSize: 9, textAlign: 'right' },
	emptyActivity: {
		minHeight: 190,
		marginTop: Spacing.medium,
		padding: Spacing.large,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 1,
		borderStyle: 'dashed',
		borderColor: '#DCCFC2',
		borderRadius: 18,
		backgroundColor: '#FBF8F4',
	},
	emptyIcon: {
		width: 48,
		height: 48,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 24,
		backgroundColor: '#F0E4D7',
	},
	emptyText: {
		maxWidth: 260,
		marginTop: 14,
		color: Colors.muted,
		fontFamily: Fonts.sans,
		fontSize: 14,
		lineHeight: 21,
		textAlign: 'center',
	},
	rtlText: {
		textAlign: 'right',
		writingDirection: 'rtl',
	},
	pressed: { opacity: 0.65 },
});
